server:
  port: ${LOCAL_PORT}
  servlet:
    context-path: ${CONTEXT_PATH}
  forward-headers-strategy: framework

spring:
  profiles.active: ${SPRING_PROFILE}
  application:
    name: fam-sub-be
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: ${app.api-domain}${server.servlet.context-path}/login/oauth2/code/google

app:
  mail:
    zepto:
      api-url: https://api.zeptomail.eu/v1.1/email
      api-key: ${ZEPTO_API_KEY}
      from-address: noreply@almonium.com
      from-name: FamSub
  payment:
    methods:
      mono:
        name: Mono
        currency: ₴
        number: "4441111068471360"
      privat:
        name: Privat
        currency: ₴
        number: "5169360022967743"
