app:
  web-domain: http://localhost:9000
  api-domain: http://localhost:${server.port}

server:
  port: ${LOCAL_PORT}
  servlet:
    context-path: ${CONTEXT_PATH}
  forward-headers-strategy: framework

spring:
  profiles.active: ${SPRING_PROFILE}
  application:
    name: fam-sub-be
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.zoho.eu
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      timeout: 3000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: ${app.api-domain}${server.servlet.context-path}/login/oauth2/code/google
